### ISSUE TITLE
i want to find somebody to automate a daily trading strategy

### ISSUE THREAD

**Issue by MrReherfx** [jonromero/forex_algotrading#15]
i have a few ideas 
 when the second daily candle close (above for buy) (below for sell)  
i want to start building a postion in the direction of the trend 
following day i want to take a postion when prices breaks and retest 
the previous day high or low on the 1 hour
every daily candle that closes above or below the 5 ema i want to add to my postion using
1 hour break and retest of he previous day high or using the days opening price 30 min timeframe after 9 pm eastern
close all postion on the first close back below/above the 5 ema
@jonromero

**Comment by wayneadams** [comment]
This doesn't seem like an issue that the project should handle.

**Comment by jonromero** [comment]
Hey @MrReherfx, @wayneadams is kinda right :D
