### ISSUE TITLE
Support and resistance might be rolling

### ISSUE THREAD

**Issue by femtotrader** [jonromero/forex_algotrading#4]
Hello,

Currently ml.py use whole data to define support/resistance lines

![capture d ecran 2016-09-11 a 11 45 36](https://cloud.githubusercontent.com/assets/5049737/18416443/7f025e0a-7815-11e6-96e2-07bbd62d2950.png)

but this kind of "indicator" might be rolling (with a given window width)

Kind regards

**Comment by jonromero** [comment]
Yes correct. The whole dataset is fed in this example. The full implementation has only the last three months.
